// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://p2mhk2lp55bgbdegmuhgehaite.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-6yifxybeffblpkgcpdqouyw5um",
    "aws_cognito_identity_pool_id": "us-west-2:404cd889-6546-460c-857a-61bac3b0d5a7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_PtaxKvaSL",
    "aws_user_pools_web_client_id": "6csm1dbb8v3qa86k4ofcvmhg6k"
};


export default awsmobile;
